import { useMemo, useState, type CSSProperties } from "react";
import { defaultAcademicState, loadAcademicState, saveAcademicState, type AcademicDiscipline } from "./lib/nexo/academicState";

type Activity = { id: string; title: string; disciplineCode: string; type: "Aula" | "Exercício" | "Trabalho"; dueDate: string; minutes: number; done: boolean };
type EventItem = { id: string; title: string; date: string; time: string; disciplineCode: string; kind: "Aula" | "Prova" | "Entrega" | "Outro" };
type EditableDiscipline = AcademicDiscipline & { examDate?: string };

const ACTIVITY_KEY = "nexo-admin-activities";
const EVENT_KEY = "nexo-admin-events";
function read<T>(key: string, fallback: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function write<T>(key: string, value: T) { localStorage.setItem(key, JSON.stringify(value)); }
function daysUntil(date: string) { if (!date) return 0; const now = new Date(); const target = new Date(`${date}T12:00:00`); return Math.max(0, Math.ceil((target.getTime() - now.getTime()) / 86400000)); }
function todayISO() { return new Date().toISOString().slice(0, 10); }
function emptyDiscipline(): EditableDiscipline { return { code: "", name: "", lessons: 0, lessonsDone: 0, exercises: 0, exercisesDone: 0, assignments: 0, assignmentsDone: 0, exam: "", daysUntilExam: 0, examDate: "" }; }

function Admin() {
  const [tab, setTab] = useState<"overview" | "disciplines" | "activities" | "agenda">("overview");
  const [disciplines, setDisciplines] = useState<AcademicDiscipline[]>(() => loadAcademicState());
  const [activities, setActivities] = useState<Activity[]>(() => read<Activity[]>(ACTIVITY_KEY, []));
  const [events, setEvents] = useState<EventItem[]>(() => read<EventItem[]>(EVENT_KEY, []));
  const [editing, setEditing] = useState<EditableDiscipline | null>(null);
  const [activity, setActivity] = useState<Activity>({ id: "", title: "", disciplineCode: "", type: "Aula", dueDate: todayISO(), minutes: 30, done: false });
  const [event, setEvent] = useState<EventItem>({ id: "", title: "", date: todayISO(), time: "19:00", disciplineCode: "", kind: "Aula" });
  const [notice, setNotice] = useState("");
  const stats = useMemo(() => ({ disciplines: disciplines.length, activities: activities.filter(a => !a.done).length, events: events.length, pending: disciplines.reduce((sum, d) => sum + d.lessons - d.lessonsDone + d.exercises - d.exercisesDone + d.assignments - d.assignmentsDone, 0) }), [disciplines, activities, events]);
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2200); };

  function saveDiscipline() {
    if (!editing?.code.trim() || !editing.name.trim()) return flash("Informe código e nome da disciplina.");
    const clean: AcademicDiscipline = { ...editing, code: editing.code.trim().toUpperCase(), lessons: Math.max(0, editing.lessons), lessonsDone: Math.min(Math.max(0, editing.lessonsDone), Math.max(0, editing.lessons)), exercises: Math.max(0, editing.exercises), exercisesDone: Math.min(Math.max(0, editing.exercisesDone), Math.max(0, editing.exercises)), assignments: Math.max(0, editing.assignments), assignmentsDone: Math.min(Math.max(0, editing.assignmentsDone), Math.max(0, editing.assignments)), daysUntilExam: daysUntil(editing.examDate ?? "") };
    const next = disciplines.some(d => d.code === clean.code) ? disciplines.map(d => d.code === clean.code ? clean : d) : [...disciplines, clean];
    setDisciplines(next); saveAcademicState(next); setEditing(null); flash("Disciplina salva. O planejamento já usa os novos dados.");
  }
  function removeDiscipline(code: string) { if (!confirm("Excluir esta disciplina?")) return; const next = disciplines.filter(d => d.code !== code); setDisciplines(next); saveAcademicState(next); setActivities(current => { const filtered = current.filter(a => a.disciplineCode !== code); write(ACTIVITY_KEY, filtered); return filtered; }); flash("Disciplina removida."); }
  function saveActivity() {
    if (!activity.title.trim() || !activity.disciplineCode) return flash("Informe atividade e disciplina.");
    const item = { ...activity, id: activity.id || `activity-${Date.now()}`, title: activity.title.trim(), minutes: Math.max(5, Number(activity.minutes) || 30) };
    const next = activity.id ? activities.map(a => a.id === item.id ? item : a) : [...activities, item];
    setActivities(next); write(ACTIVITY_KEY, next); setActivity({ id: "", title: "", disciplineCode: disciplines[0]?.code ?? "", type: "Aula", dueDate: todayISO(), minutes: 30, done: false }); flash("Atividade salva.");
  }
  function saveEvent() {
    if (!event.title.trim() || !event.date) return flash("Informe título e data.");
    const item = { ...event, id: event.id || `event-${Date.now()}`, title: event.title.trim() };
    const next = event.id ? events.map(e => e.id === item.id ? item : e) : [...events, item];
    next.sort((a, b) => `${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)); setEvents(next); write(EVENT_KEY, next); setEvent({ id: "", title: "", date: todayISO(), time: "19:00", disciplineCode: disciplines[0]?.code ?? "", kind: "Aula" }); flash("Evento salvo na agenda.");
  }
  function resetDemo() { if (!confirm("Voltar aos dados iniciais? Isso substitui as alterações feitas neste navegador.")) return; setDisciplines(defaultAcademicState); saveAcademicState(defaultAcademicState); setActivities([]); write(ACTIVITY_KEY, []); setEvents([]); write(EVENT_KEY, []); flash("Dados iniciais restaurados."); }
  const field = (label: string, value: string | number, onChange: (value: string) => void, type = "text") => <label style={{ display: "grid", gap: 6, fontSize: 11, color: "var(--muted)" }}><span>{label}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} style={inputStyle} /></label>;

  return <div className="app"><header className="topbar"><div className="brand-area"><span className="brand">NEXO</span><span className="brand-subtitle">CMS · Administração</span></div><nav className="desktop-nav"><a href="/">Hoje</a><a href="/agenda">Agenda</a><a href="/disciplinas">Disciplinas</a><a href="/progresso">Progresso</a></nav><div style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ fontSize: 11, color: "var(--muted)" }}>Painel de conteúdo</span><a href="/" style={{ fontSize: 12, fontWeight: 700, color: "var(--lagoon)" }}>Sair →</a></div></header><main className="main-content" style={{ maxWidth: 1240 }}><section className="welcome" style={{ alignItems: "flex-start" }}><div><p className="eyebrow">CENTRAL DE ADMINISTRAÇÃO</p><h1 style={{ fontSize: "clamp(32px, 5vw, 50px)" }}>Coloque o NEXO para funcionar.</h1><p className="welcome-text">Cadastre o semestre, atividades, provas e compromissos. O aluno não precisa editar nada: o planejamento usa estes dados.</p></div><button onClick={resetDemo} style={dangerButton}>Restaurar dados de demonstração</button></section>
      <div style={tabBar}>{([['overview','Visão geral'],['disciplines','Disciplinas'],['activities','Atividades'],['agenda','Agenda']] as const).map(([key,label]) => <button key={key} onClick={() => setTab(key)} style={tab === key ? activeTab : tabButton}>{label}</button>)}</div>
      {notice && <div style={noticeStyle}>✓ {notice}</div>}
      {tab === "overview" && <section style={cardGrid}><Stat title="Disciplinas" value={stats.disciplines} text="cadastradas" /><Stat title="Pendências" value={stats.pending} text="itens ainda abertos" /><Stat title="Atividades" value={stats.activities} text="pendentes" /><Stat title="Agenda" value={stats.events} text="eventos cadastrados" /><article style={wideCard}><div><p className="eyebrow">COMO USAR HOJE</p><h2 style={h2}>Seu CMS mínimo viável</h2><p style={paragraph}>1. Cadastre ou ajuste as disciplinas. 2. Coloque quantidade total e concluída. 3. Cadastre provas no campo de data. 4. Registre atividades e eventos. 5. Volte para <b>Hoje</b> ou <b>Agenda</b>: os dados salvos neste navegador serão usados pelo planejamento.</p></div><button style={primaryButton} onClick={() => setTab("disciplines")}>Começar cadastro →</button></article></section>}
      {tab === "disciplines" && <section><div style={sectionHeader}><div><p className="eyebrow">BASE ACADÊMICA</p><h2 style={h2}>Disciplinas</h2></div><button style={primaryButton} onClick={() => setEditing(emptyDiscipline())}>+ Nova disciplina</button></div>{editing && <div style={formCard}><div style={sectionHeader}><div><p className="eyebrow">EDIÇÃO</p><h3 style={h3}>{disciplines.some(d => d.code === editing.code) ? "Editar disciplina" : "Nova disciplina"}</h3></div><button style={ghostButton} onClick={() => setEditing(null)}>Cancelar</button></div><div style={formGrid}>{field("Código", editing.code, v => setEditing({ ...editing, code: v }))}{field("Nome", editing.name, v => setEditing({ ...editing, name: v }))}{field("Total de aulas", editing.lessons, v => setEditing({ ...editing, lessons: Number(v) }), "number")}{field("Aulas concluídas", editing.lessonsDone, v => setEditing({ ...editing, lessonsDone: Number(v) }), "number")}{field("Total de exercícios", editing.exercises, v => setEditing({ ...editing, exercises: Number(v) }), "number")}{field("Exercícios concluídos", editing.exercisesDone, v => setEditing({ ...editing, exercisesDone: Number(v) }), "number")}{field("Total de trabalhos", editing.assignments, v => setEditing({ ...editing, assignments: Number(v) }), "number")}{field("Trabalhos concluídos", editing.assignmentsDone, v => setEditing({ ...editing, assignmentsDone: Number(v) }), "number")}{field("Data da próxima prova", editing.examDate ?? "", v => setEditing({ ...editing, exam: v ? new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "short" }).toUpperCase() : "", daysUntilExam: daysUntil(v), examDate: v }), "date")}</div><div style={{ display: "flex", justifyContent: "flex-end", marginTop: 16 }}><button style={primaryButton} onClick={saveDiscipline}>Salvar disciplina</button></div></div>}{disciplines.map((d) => <article key={d.code} style={listCard}><div><span className="task-type">{d.code}</span><h3 style={h3}>{d.name}</h3><p style={paragraph}>{d.lessonsDone}/{d.lessons} aulas · {d.exercisesDone}/{d.exercises} exercícios · {d.assignmentsDone}/{d.assignments} trabalhos · prova {d.exam || "não cadastrada"}</p></div><div style={{ display: "flex", gap: 8 }}><button style={ghostButton} onClick={() => setEditing({ ...d, examDate: "" })}>Editar</button><button style={deleteButton} onClick={() => removeDiscipline(d.code)}>Excluir</button></div></article>)}</section>}
      {tab === "activities" && <section><div style={sectionHeader}><div><p className="eyebrow">CONTEÚDO E CARGA</p><h2 style={h2}>Atividades</h2></div></div><div style={formCard}><div style={formGrid}>{field("Título", activity.title, v => setActivity({ ...activity, title: v }))}<label style={labelStyle}><span>Disciplina</span><select value={activity.disciplineCode} onChange={e => setActivity({ ...activity, disciplineCode: e.target.value })} style={inputStyle}>{disciplines.map(d => <option key={d.code} value={d.code}>{d.name}</option>)}</select></label><label style={labelStyle}><span>Tipo</span><select value={activity.type} onChange={e => setActivity({ ...activity, type: e.target.value as Activity['type'] })} style={inputStyle}><option>Aula</option><option>Exercício</option><option>Trabalho</option></select></label>{field("Prazo", activity.dueDate, v => setActivity({ ...activity, dueDate: v }), "date")}{field("Minutos", activity.minutes, v => setActivity({ ...activity, minutes: Number(v) }), "number")}</div><button style={primaryButton} onClick={saveActivity}>{activity.id ? "Atualizar atividade" : "Cadastrar atividade"}</button></div>{activities.length === 0 ? <Empty text="Nenhuma atividade cadastrada ainda." /> : activities.map(a => <article key={a.id} style={listCard}><div><span className="task-type">{a.type} · {a.dueDate}</span><h3 style={h3}>{a.title}</h3><p style={paragraph}>{disciplines.find(d => d.code === a.disciplineCode)?.name ?? a.disciplineCode} · {a.minutes} min</p></div><div style={{ display: "flex", gap: 8 }}><button style={ghostButton} onClick={() => setActivity(a)}>Editar</button><button style={deleteButton} onClick={() => { const next = activities.filter(x => x.id !== a.id); setActivities(next); write(ACTIVITY_KEY, next); }}>Excluir</button></div></article>)}</section>}
      {tab === "agenda" && <section><div style={sectionHeader}><div><p className="eyebrow">COMPROMISSOS</p><h2 style={h2}>Agenda do semestre</h2></div></div><div style={formCard}><div style={formGrid}>{field("Título", event.title, v => setEvent({ ...event, title: v }))}{field("Data", event.date, v => setEvent({ ...event, date: v }), "date")}{field("Horário", event.time, v => setEvent({ ...event, time: v }), "time")}<label style={labelStyle}><span>Disciplina</span><select value={event.disciplineCode} onChange={e => setEvent({ ...event, disciplineCode: e.target.value })} style={inputStyle}><option value="">Geral</option>{disciplines.map(d => <option key={d.code} value={d.code}>{d.name}</option>)}</select></label><label style={labelStyle}><span>Tipo</span><select value={event.kind} onChange={e => setEvent({ ...event, kind: e.target.value as EventItem['kind'] })} style={inputStyle}><option>Aula</option><option>Prova</option><option>Entrega</option><option>Outro</option></select></label></div><button style={primaryButton} onClick={saveEvent}>{event.id ? "Atualizar evento" : "Adicionar à agenda"}</button></div>{events.length === 0 ? <Empty text="Nenhum evento cadastrado ainda." /> : events.map(e => <article key={e.id} style={listCard}><div><span className="task-type">{e.kind} · {e.date} · {e.time}</span><h3 style={h3}>{e.title}</h3><p style={paragraph}>{disciplines.find(d => d.code === e.disciplineCode)?.name ?? "Geral"}</p></div><div style={{ display: "flex", gap: 8 }}><button style={ghostButton} onClick={() => setEvent(e)}>Editar</button><button style={deleteButton} onClick={() => { const next = events.filter(x => x.id !== e.id); setEvents(next); write(EVENT_KEY, next); }}>Excluir</button></div></article>)}</section>}
    </main></div>;
}
function Stat({ title, value, text }: { title: string; value: number; text: string }) { return <article style={statCard}><span className="eyebrow">{title}</span><strong style={{ fontFamily: "Sora", fontSize: 36, color: "var(--deep)" }}>{value}</strong><span style={{ color: "var(--muted)", fontSize: 11 }}>{text}</span></article>; }
function Empty({ text }: { text: string }) { return <div style={{ ...listCard, justifyContent: "center", color: "var(--muted)" }}>{text}</div>; }
const inputStyle: CSSProperties = { width: "100%", padding: "11px 12px", border: "1px solid var(--border)", borderRadius: 10, background: "white", color: "var(--deep)", outline: "none" };
const labelStyle: CSSProperties = { display: "grid", gap: 6, fontSize: 11, color: "var(--muted)" };
const tabBar: CSSProperties = { display: "flex", gap: 7, flexWrap: "wrap", marginBottom: 24, padding: 5, border: "1px solid var(--border)", borderRadius: 14, background: "var(--cream)" };
const tabButton: CSSProperties = { border: 0, background: "transparent", color: "var(--muted)", padding: "10px 14px", borderRadius: 10, fontWeight: 700, fontSize: 11 };
const activeTab: CSSProperties = { ...tabButton, background: "var(--lagoon-light)", color: "var(--lagoon)" };
const primaryButton: CSSProperties = { border: 0, padding: "11px 15px", borderRadius: 10, background: "var(--deep)", color: "white", fontWeight: 700, fontSize: 11, cursor: "pointer" };
const ghostButton: CSSProperties = { border: "1px solid var(--border)", padding: "9px 12px", borderRadius: 9, background: "white", color: "var(--deep)", fontWeight: 700, fontSize: 10, cursor: "pointer" };
const deleteButton: CSSProperties = { ...ghostButton, color: "var(--danger)" };
const dangerButton: CSSProperties = { ...ghostButton, color: "var(--danger)" };
const statCard: CSSProperties = { minHeight: 135, padding: 22, display: "flex", flexDirection: "column", justifyContent: "center", gap: 5, border: "1px solid var(--border)", borderRadius: 18, background: "var(--cream)" };
const wideCard: CSSProperties = { gridColumn: "1 / -1", padding: 24, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 25, border: "1px solid var(--border)", borderRadius: 20, background: "var(--lagoon-light)" };
const cardGrid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 14 };
const formGrid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 14, marginBottom: 16 };
const formCard: CSSProperties = { padding: 22, marginBottom: 16, border: "1px solid var(--border)", borderRadius: 18, background: "var(--cream)" };
const listCard: CSSProperties = { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20, padding: 18, marginBottom: 9, border: "1px solid var(--border)", borderRadius: 15, background: "rgba(255,253,249,.9)" };
const sectionHeader: CSSProperties = { display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 20, marginBottom: 18 };
const h2: CSSProperties = { margin: 0, fontFamily: "Sora", fontSize: 28, color: "var(--deep)" };
const h3: CSSProperties = { margin: "5px 0 4px", fontFamily: "Sora", fontSize: 16, color: "var(--deep)" };
const paragraph: CSSProperties = { margin: 0, color: "var(--muted)", fontSize: 11, lineHeight: 1.55 };
const noticeStyle: CSSProperties = { position: "fixed", right: 22, bottom: 22, zIndex: 200, padding: "12px 16px", borderRadius: 12, background: "var(--deep)", color: "white", fontSize: 11, fontWeight: 700, boxShadow: "var(--shadow)" };
export default Admin;
