import { useMemo, useState } from "react";
import { generateDailyMissions } from "./lib/nexo/dailyMissions";
import { applyMissionCompletion, loadAcademicState, saveAcademicState } from "./lib/nexo/academicState";

type AgendaItem = { id: string; day: string; date: string; time: string; subject: string; title: string; type: string; duration: string; status: "next" | "pending" | "done" };

function Agenda() {
  const [items, setItems] = useState<AgendaItem[]>(() => {
    const state = loadAcademicState();
    const workload = state.map(({ code, name, lessons, lessonsDone, exercises, exercisesDone, assignments, assignmentsDone, daysUntilExam }) => ({ code, name, pendingLessons: lessons - lessonsDone, pendingExercises: exercises - exercisesDone, pendingAssignments: assignments - assignmentsDone, daysUntilExam }));
    const generated = generateDailyMissions(workload, 90);
    return [...generated.map((mission, index) => ({ id: mission.id, day: "Hoje", date: "1 SET", time: index === 0 ? "Agora" : `${19 + index}:00`, subject: mission.subject, title: mission.title, type: mission.type, duration: `${mission.duration} min`, status: index === 0 ? "next" as const : "pending" as const })), { id: "live-stat", day: "Hoje", date: "1 SET", time: "19:00", subject: "Estatística e Probabilidade", title: "Aula ao vivo", type: "Aula ao vivo", duration: "1h30", status: "pending" as const }];
  });
  const completed = useMemo(() => items.filter((item) => item.status === "done").length, [items]);
  function markDone(id: string) { const item = items.find((entry) => entry.id === id); if (!item || item.id === "live-stat") return; saveAcademicState(applyMissionCompletion(loadAcademicState(), id)); setItems((current) => { const updated = current.map((entry) => entry.id === id ? { ...entry, status: "done" as const } : entry); const nextPending = updated.find((entry) => entry.status !== "done"); return updated.map((entry) => ({ ...entry, status: entry.status === "done" ? "done" as const : entry.id === nextPending?.id ? "next" as const : "pending" as const })); }); }

  return <div className="app"><header className="topbar"><div className="brand-area"><span className="brand">NEXO</span><span className="brand-subtitle">Assistente Acadêmico</span></div><nav className="desktop-nav"><a href="/">Hoje</a><a className="active" href="/agenda">Agenda</a><a href="/disciplinas">Disciplinas</a><a href="/progresso">Progresso</a></nav><div className="student"><div className="avatar">E</div><div className="student-info"><strong>Estudante</strong><span>Meu semestre</span></div></div></header><main className="main-content"><section className="welcome"><div><p className="eyebrow">PLANEJAMENTO ACADÊMICO</p><h1>Sua semana,<br />organizada.</h1><p className="welcome-text">Você não precisa descobrir quando fazer cada coisa.<br />O NEXO distribui o trabalho para você chegar às provas preparado.</p></div></section><section className="agenda-container"><div className="agenda-header"><div><p className="eyebrow">TERÇA-FEIRA · 1 DE SETEMBRO</p><h2>Plano de hoje</h2></div><div className="agenda-summary"><strong>{completed}</strong><span>de {items.length} concluídas</span></div></div><div className="planner-banner"><span>🧠</span><div><strong>Agenda calculada pelo NEXO</strong><p>As tarefas abaixo usam as pendências acadêmicas atuais para definir a próxima sequência.</p></div></div><div className="agenda-timeline">{items.map((item, index) => { const isDone = item.status === "done"; const isNext = item.status === "next"; return <div className={`agenda-item ${isDone ? "done" : ""} ${isNext ? "next" : ""}`} key={item.id}><div className="agenda-time">{item.time}</div><div className="timeline-line"><span className="timeline-dot">{isDone ? "✓" : ""}</span>{index < items.length - 1 && <span className="timeline-connector" />}</div><article className="agenda-card"><div className="agenda-card-top"><div><span className="task-type">{item.type}</span><h3>{item.title}</h3><p>{item.subject}</p></div><span className="agenda-duration">⏱ {item.duration}</span></div><div className="agenda-card-footer">{isNext && <span className="next-badge">PRÓXIMO</span>}{isDone && <span className="done-badge">✓ CONCLUÍDO</span>}{!isDone && item.id !== "live-stat" && <button className="agenda-complete" onClick={() => markDone(item.id)}>Marcar como concluído <span>→</span></button>}{item.id === "live-stat" && <span className="next-badge">AULA AO VIVO</span>}</div></article></div>; })}</div></section></main><button className="assistant-button" onClick={() => alert("O Assistente de Estudos será conectado à IA.")}><span className="assistant-sparkle">✨</span><span>Preciso de ajuda</span></button></div>;
}
export default Agenda;
